### ISSUE TITLE
"TypeError: Cannot read property 'createHref' of undefined" if used with React Router

### ISSUE THREAD

**Issue by mhaagens** [FormidableLabs/rapscallion#8] opened 2017-02-03 11:18 UTC
If used with React Router I'm getting
```
TypeError: Cannot read property 'createHref' of undefined
```

App.js:

```
import React, { Component } from 'react'
import { Route } from 'react-router-dom'
import Home from './Home'

export default class App extends Component {
	render() {
		return (
			<div>
				<Route path="/" component={Home} />
			</div>
		)
	}
}
```

Home.js:
```
import React, {Component} from 'react'

export default class Home extends Component {
	constructor(props) {
		super(props)
	}
	render() {
		return (
			<div className="home">Test</div>
		)
	}
}
```

Server:
```
require('babel-register');
require('babel-polyfill');
import express from "express";
import path from "path";
import App from './App';
import React from 'react';
import { renderToStream, toNodeStream, streamTemplate } from "rapscallion";
import { StaticRouter } from 'react-router-dom';

const app = express();

app.use("/", (req, res) => {

    const context = {};

    const application = renderToStream(
        <StaticRouter location={req.url} context={context}>
            <App />
        </StaticRouter>
    );

    const html = streamTemplate`<!doctype html><html>
      <head>
        <title>Test</title>
      </head>
      <body>
        <div id="root">${application}</div>
      </body>
    </html>`

    if (context.url) {
        res.writeHead(302, { Location: context.url });
        res.end();
    } else {
        toNodeStream(html).pipe(res)
    }

});

app.listen(3000, () => {
    console.log("App listening on port 3000");
});
```

**Comment by mhaagens** [comment] 2017-02-03 12:04
Seems like a context issue? All props sent to the <StaticRouter /> are undefined.

**Comment by divmain** [comment] 2017-02-03 18:21
Perfect, thanks for such a great repro!

**Comment by divmain** [comment] 2017-02-03 19:22
This might be due to #9.  If `react-router` relies on an HOC's `setState` method, that doesn't work yet.  If the fix to #9 doesn't resolve this, I'll dig in deeper!

**Comment by mhaagens** [comment] 2017-02-03 19:54
Sounds good, I'll test it as soon as the fix is up. Thanks!

**Comment by divmain** [comment] 2017-02-04 03:06
@mhaagens I'm having trouble moving forward with this issue.  From what I can tell `react-router-dom` is not a for-realz package.  It appears to be a single, empty `index.js` when I pull it down from `npm`.

The `<Router>` component is present in `react-router` but not `<StaticRouter>`.  Any thoughts?

**Comment by divmain** [comment] 2017-02-04 03:31
Heh.  It looks like this is completely unrelated to `rapscallion`, although it definitely wasn't obvious why :)  If you `npm install react-router-dom@next`, your example should work :+1:.  I've posted the exact repro I'm using [here](https://gist.github.com/divmain/409461325d8098dfab08ff46b38cbef8).  Let me know if you run into any other issues with RRv4!

**Comment by mhaagens** [comment] 2017-02-04 09:03
Hi! I had react-router-dom@next installed and it works if I keep everything in one file, but it breaks as soon as I move the components out of the index file and import them instead (export default class App etc...), so I don't think the empty package was the problem. If it's not too much trouble could you try to import your components and see if that works for you?

**Comment by divmain** [comment] 2017-02-04 09:18
Very strange.  I'll give it another look!

**Comment by mhaagens** [comment] 2017-02-04 09:19
Thanks, appreciate it!

**Comment by divmain** [comment] 2017-02-04 09:56
I've isolated the difference between our two examples, and it wasn't the imports.  It was the fact that `<Route>` was wrapped in a `<div>` in yours but not mine.  I'm looking closer to see what might be causing the issue.  Thanks for persisting!

**Comment by divmain** [comment] 2017-02-04 10:04
Found it!  Context wasn't being passed down to children of `<div>`s.  Fix is in and published with `v1.0.7`.  It wasn't showing `TypeError: Cannot read property 'createHref' of undefined` (I think that was probably `react-router-dom`?) but instead was showing `TypeError: Cannot read property 'location' of undefined`.

Anyway, can you take a look and confirm all is well?

**Comment by mhaagens** [comment] 2017-02-04 10:37
Awesome, that worked! Yeah I got that error as well, but all is well now!
I'm going to test properly a little later, because I had to remove the constructor from my components to get it to work, I had;
```
export default class Home extends Component {
	constructor(props) {
		super(props)
	}
	render() {
		return (
			<div className="home">
			Home page
			</div>
		)
	}
}
```
which gave me
```
Unhandled promise rejection (rejection id: 1):  TypeError: Unknown node of type: undefined
```

It started working when I removed the constructor. Thanks so much for fixing this, I'm really excited to benchmark the performance later. Cheers!

**Comment by divmain** [comment] 2017-02-04 10:45
The constructor thing may be due to the fact that constructors accept two arguments: `props` and `context`.  So you might want to do:

```javascript
constructor(...args) {
  super(...args)
}
```

or 

```javascript
constructor(props, context) {
  super(props, context)
}
```

If that's not the case though and you notice problems somewhere, let me know.  I'm eager to iron out all that I can before doing a more public release.

**Comment by mhaagens** [comment] 2017-02-04 11:31
I removed the constructor and tried using a subcomponent, like this;
```
export default class Home extends Component {
	render() {
		return (
			<div className="home">
			<Helmet
			    title="Home"
			    meta={[
			        {"name": "description", "content": "Helmet application"}
			    ]}
			/>
			Home
			</div>
		)
	}
}
```
and then I get the same ```Unhandled promise rejection (rejection id: 1):  TypeError: Unknown node of type: undefined``` error. I also tried wrapping my routes in the main app in a div, like this;

```
import React, { Component } from 'react'
import { Switch, Route, Link } from 'react-router-dom'
import LazyRoute from './LazyRoute'

export default class App extends Component {
	componentDidMount() {
		console.log('BUILD_TARGET: ', process.env.BUILD_TARGET)
		console.log('process.env.NODE_ENV: ', process.env.NODE_ENV)
	}
	render() {
		return (
			<div>
				<Link to="/">Home</Link>
				<Link to="/subpage">Subroute</Link>
				<div>
					<Switch>
						<Route path="/" exact render={() => LazyRoute('./components/Home')} />
						<Route path="/subpage" render={() => LazyRoute('./components/Subpage')} />
						<Route render={() => LazyRoute('./components/NoMatch')} />
					</Switch>
				</div>
			</div>
		)
	}
}
```
which gives the same error. I removed the lazy route loading and imported the components normally and got the same error, so that's not the issue. Seems like an issue when routes are wrapped or are wrapping divs or components?

**Comment by divmain** [comment] 2017-02-04 19:26
Oh bother.. I'll give this another try.

**Comment by divmain** [comment] 2017-02-05 00:49
Hey @mhaagens - I've created a temporary repo [here](https://github.com/divmain/rapscallion-rr4) to give us something better to iterate on.  I'm working to reproduce the error you see here, and if I get it working you can try to break it again :)  Thanks again for your help -it's been very productive!

**Comment by divmain** [comment] 2017-02-05 05:57
There's some underlying issue with my renderer and `react-side-effect` / `react-helmet`.  Something strange is going on there with component initialization...

**Closed** 2017-02-05 07:28 UTC
Labels: bug

**Comment by divmain** [comment] 2017-02-05 07:35
Alright, this was an intense rabbit-hole, but I think I have it...  You may interested in the ultimate fix - it was a three-line fix, but obscure and confusing enough that it warranted a 41-line comment :1st_place_medal: 

The [test repo](https://github.com/divmain/rapscallion-rr4) has been updated with a working rapscallion + RRv4 + Helmet application nearly identical to what you posted.  Feel free to push a change to that repo if you notice something else amiss.

**Comment by divmain** [comment] 2017-02-05 07:41
And released in `rapscallion@1.1.1`.

**Comment by mhaagens** [comment] 2017-02-05 07:59
Hey, sorry for replying so late, I think we're on completely different timezones.
I installed @1.1.1 and everything works beautifully now!
And yeah took a look at the comment for the fix, that must've taken a bit to figure out!
Thanks so much for fixing things over the weekend, really appreciate it and I'll definitely help champion this library. eventually I plan on using it for work on a production site with pretty heavy page load, so it'll be fun to see how it performs!
Thanks again :)

**Comment by divmain** [comment] 2017-02-05 08:16
Awesome. Next up for me is to look into back pressure for the streaming mode. It'd be fantastic if evaluation of the DOM tree haulted upon network traffic congestion.

**Comment by mhaagens** [comment] 2017-02-05 08:30
So it would just send down the stream template but skip server render of the application?

**Comment by divmain** [comment] 2017-02-05 20:27
Well, it would evaluate whatever the stream was ready for. In most cases, yes, it would at least start by sending the first bits of the template. And possibly the first, say, 1000 characters of your components HTML. But at that point, if the outgoing network connection got backed up, evaluation of your react component would pause until the buffer had room. 

One random thought that was triggered by this conversation: It is not clear from the README, but the stream templates are composable too. So you can define templates in fragments and compose them together however you'd like. I'll open an issue to add some documentation there.
