### ISSUE TITLE
Runaway promise error when using this library with Bluebird

### ISSUE THREAD

**Issue by genui-eeshan** [FormidableLabs/rapscallion#119] opened 2017-12-05 21:40 UTC
When using this library with Bluebird, Bluebird throws a runaway promise error for the following: 

```
(node:1528) Warning: a promise was created in a handler at node_modules/rapscallion/lib/consumers/node-stream.js:42:9 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (node_modules/bluebird/js/release/promise.js:196:13)
```

More information about the error can be found here: http://goo.gl/rRqMUw

**Comment by genui-eeshan** [comment] 2017-12-05 21:42
A simple fix that worked locally was adding ```return null``` before the catch on line 44.

**Comment by ryan-roemer** [comment] 2017-12-06 23:06
We'd ❤️  a PR with a regression test!

**Comment by genui-eeshan** [comment] 2017-12-11 17:56
@ryan-roemer Someone created a PR for this. #111 

What's it missing to be pushed in?

**Comment by ryan-roemer** [comment] 2017-12-18 20:26
@genui-eeshan -- Glad to hear it's the same issue since L44 isn't in that PR. Added a reference in https://github.com/FormidableLabs/rapscallion/pull/111 to close this issue when merged.

**Comment by ryan-roemer** [comment] 2018-10-31 22:52
Fixed in #124 if I'm tracking things correctly.

@ethersage -- is that right?

**Closed by ryan-roemer** 2018-10-31 22:52 UTC

**Comment by ethersage** [comment] 2018-11-01 04:30
@ryan-roemer Correct. Have not released a patch version yet though.
